"""Tenant provisioner — creates and manages per-org Docker containers."""
import os
import secrets
import uuid
from datetime import datetime, timezone

import docker
import docker.errors


# ── Port allocation ───────────────────────────────────────────────────────────

def allocate_port(used_ports: list[int]) -> int:
    """Return lowest available port starting from 6001."""
    port = 6001
    while port in used_ports:
        port += 1
    return port


def generate_db_password() -> str:
    return secrets.token_urlsafe(24)


# ── Compose file ──────────────────────────────────────────────────────────────

def write_compose_file(slug: str, port: int, password: str) -> None:
    """Write a docker-compose.yml for the tenant to /mnt/tenants/{slug}/."""
    compose_dir = f"/mnt/tenants/{slug}"
    os.makedirs(compose_dir, exist_ok=True)
    content = f"""# Tenant: {slug}
# Auto-generated by Worsyn — do not edit manually
services:
  db:
    image: postgres:16-alpine
    container_name: worsyn-tenant-{slug}-db
    environment:
      POSTGRES_USER: {slug}
      POSTGRES_PASSWORD: {password}
      POSTGRES_DB: {slug}
    ports:
      - "{port}:5432"
    volumes:
      - /mnt/tenants/{slug}/data:/var/lib/postgresql/data
    restart: unless-stopped
"""
    with open(f"{compose_dir}/docker-compose.yml", "w") as f:
        f.write(content)


# ── Docker operations ─────────────────────────────────────────────────────────

async def provision_tenant(org_id_str: str, slug: str, port: int, password: str) -> None:
    """Background task: spin up the tenant's PostgreSQL container."""
    from sqlalchemy import select
    from app.db.session import AsyncSessionLocal
    from app.models.models import Tenant

    org_id = uuid.UUID(org_id_str)
    async with AsyncSessionLocal() as db:
        result = await db.execute(select(Tenant).where(Tenant.org_id == org_id))
        tenant = result.scalar_one_or_none()
        if not tenant:
            return
        try:
            write_compose_file(slug, port, password)
            data_dir = f"/mnt/tenants/{slug}/data"
            os.makedirs(data_dir, exist_ok=True)

            client = docker.from_env()
            # Remove stale container if any
            try:
                old = client.containers.get(f"worsyn-tenant-{slug}-db")
                old.remove(force=True)
            except docker.errors.NotFound:
                pass

            client.containers.run(
                "postgres:16-alpine",
                name=f"worsyn-tenant-{slug}-db",
                detach=True,
                environment={
                    "POSTGRES_USER": slug,
                    "POSTGRES_PASSWORD": password,
                    "POSTGRES_DB": slug,
                },
                ports={"5432/tcp": port},
                volumes={data_dir: {"bind": "/var/lib/postgresql/data", "mode": "rw"}},
                restart_policy={"Name": "unless-stopped"},
            )
            tenant.status = "running"
            tenant.error_msg = None
            tenant.provisioned_at = datetime.now(timezone.utc)

        except Exception as exc:
            tenant.status = "error"
            tenant.error_msg = str(exc)[:500]

        await db.commit()


def start_tenant(slug: str) -> tuple[bool, str | None]:
    try:
        client = docker.from_env()
        client.containers.get(f"worsyn-tenant-{slug}-db").start()
        return True, None
    except Exception as exc:
        return False, str(exc)


def stop_tenant(slug: str) -> tuple[bool, str | None]:
    try:
        client = docker.from_env()
        client.containers.get(f"worsyn-tenant-{slug}-db").stop()
        return True, None
    except Exception as exc:
        return False, str(exc)


def destroy_tenant(slug: str) -> tuple[bool, str | None]:
    try:
        client = docker.from_env()
        try:
            client.containers.get(f"worsyn-tenant-{slug}-db").remove(force=True)
        except docker.errors.NotFound:
            pass
        return True, None
    except Exception as exc:
        return False, str(exc)


def check_container_status(container_name: str) -> str | None:
    """Return Docker container status string or None if not found."""
    try:
        client = docker.from_env()
        return client.containers.get(container_name).status
    except docker.errors.NotFound:
        return None
    except Exception:
        return None
